config/routes.rb
R3TMS::Application.routes.draw do
  devise_for :admins
  
  match 'manage/:controller', :controller => ':controller', :action => 'index'
  match 'manage/:controller/:action', :to => ':controller/:action'
  
  match 'manage', :controller => 'orders', :action => 'track'

  match 'tracking', :controller => 'orders', :action => 'track'
  match 'track', :controller => 'orders', :action => 'track'
  
  resources :orders do
    put :complete, :on => :member
  end
  
  resources :consumables

  resources :printer_models

  resources :batches

  resources :suppliers

  resources :departments

  resources :manufacturers

  root :to => 'orders#new'
end

app/views/shared/_banner.html.erb
<div id="banner">
    <%= image_tag("header.png", :id => "logo") %>
</div>

app/views/shared/_devinfo.html.erb
<div class="devinfo">
  <p class="ver"><%= "#{Settings.about['app_full_name']} #{Settings.about['version']} - #{Settings.about['location']} #{Settings.about['year']}" %></p>
</div>

app/views/shared/_menu.html.erb
<div id="menu">
  <span class="important-button"><%= link_to "New Order", root_url %></span>
  <span class="important-button"><%= link_to "Track Orders", tracking_path %></span>
  <span class="button"><%= link_to "Order History", orders_path %></span>
  <span class="button"><%= link_to "Suppliers", suppliers_path %></span>
  <span class="button"><%= link_to "Manufacturers", manufacturers_path %></span>
  <span class="button"><%= link_to "Printers", printer_models_path %></span>
  <span class="button"><%= link_to "Consumables", consumables_path %></span>
  <span class="button"><%= link_to "Departments", departments_path %></span>
  <span class="button"><%= link_to "Batches", batches_path %></span>
  <% if admin_signed_in? %>
    <div class="login-links">You are logged in as <%= current_admin.email %>: <%= link_to "Sign out", destroy_admin_session_path, :method => :delete %>.
    </div>
  <% end %>
</div>

app/views/shared/_title.html.erb
<h1 class="title"><%= current_controller_title %></h1>