config/routes.rb
R3TMS::Application.routes.draw do
  devise_for :admins
  
  match 'manage/:controller', :controller => ':controller', :action => 'index'
  match 'manage/:controller/:action', :to => ':controller/:action'
  
  match 'manage', :controller => 'orders', :action => 'track'

  match 'tracking', :controller => 'orders', :action => 'track'
  match 'track', :controller => 'orders', :action => 'track'
  
  resources :orders do
    put :complete, :on => :member
  end
  
  resources :consumables

  resources :printer_models

  resources :batches

  resources :suppliers

  resources :departments

  resources :manufacturers

  root :to => 'orders#new'
end

app/models/department.rb
# == Schema Information
#
# Table name: departments
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Department < ActiveRecord::Base
  has_many :orders

  validates :name, :presence => true, :uniqueness => true

  attr_accessible :name
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_filter :authenticate_admin!
  
  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.paginate page: params[:page], order: 'name desc', per_page: 10

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @departments }
    end
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    @department = Department.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/new
  # GET /departments/new.json
  def new
    @department = Department.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @department = Department.find(params[:id])
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render json: @department, status: :created, location: @department }
      else
        format.html { render action: "new" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.json
  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url }
      format.json { head :ok }
    end
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<h1>Listing departments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>

<% @departments.each do |department| %>
  <tr class="<%= cycle("even", "odd") %>">
    <td><%= department.name %></td>
    <td>
      <%= link_to 'Show', department %>
      <%= link_to 'Edit', edit_department_path(department) %>
      <%= link_to 'Destroy', department, confirm: 'Are you sure?', method: :delete %>
    </td>
  </tr>
<% end %>
</table>

<br />
<p><%= will_paginate @printer_models %></p>
<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p>
  <b>Name:</b>
  <%= @department.name %>
</p>


<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>