config/routes.rb
R3TMS::Application.routes.draw do
  devise_for :admins
  
  match 'manage/:controller', :controller => ':controller', :action => 'index'
  match 'manage/:controller/:action', :to => ':controller/:action'
  
  match 'manage', :controller => 'orders', :action => 'track'

  match 'tracking', :controller => 'orders', :action => 'track'
  match 'track', :controller => 'orders', :action => 'track'
  
  resources :orders do
    put :complete, :on => :member
  end
  
  resources :consumables

  resources :printer_models

  resources :batches

  resources :suppliers

  resources :departments

  resources :manufacturers

  root :to => 'orders#new'
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id            :integer          not null, primary key
#  location      :string(255)
#  price         :decimal(3, 2)
#  order_status  :string(255)
#  department_id :integer
#  consumable_id :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class Order < ActiveRecord::Base
  attr_accessible :location, :department_id, :consumable_id, :printer_models

  belongs_to :department
  belongs_to :consumable
  has_many :printer_models, :through => :consumable

  # Possible order statuses, don't forget to add relevent scope!

  STATUS = {
              "PEN" => "Pending Dispatch",
              "AWS" => "Awaiting Stock",
              "DIS" => "Dispatched",
              "DEL" => "Deleted",
              "FOC" => "Free of Charge",
              "ADD" => "Added to Stock"
            }

  validates :location, :price, :order_status, :department_id, :consumable_id, :presence => true
  validates :order_status, :inclusion => { :in => STATUS }

  #scopes
  scope :status, ->(stat) { where("orders.order_status LIKE ?", stat) }

  scope :pending, order.status("PEN")
  scope :awaiting, order.status("AWS")
  scope :deleted, order.status("DEL")
  scope :dispatched, order.status("DIS")
  scope :free, order.status("FOC")
  scope :added, order.status("ADD")

  def calculate_order_status
    stock = self.consumable.batch_price.stock
    if stock >= 1
      self.order_status = "PEN"
    elsif stock == 0
      self.order_status = "AWS"
    end
  end

  def order_status_text
    STATUS[order_status]
  end

  def consumable_name(type=false)
    consumable = Consumable.find(self.consumable_id)
    type ? "#{consumable.full_name}, #{consumable.description} (#{consumable.kind})" : "#{consumable.full_name}, #{consumable.description}"
  end

  def printer_names
    result = []
    self.consumable.printer_models.each do |printer|
      result << printer.full_name
    end
    result.to_sentence
  end

  def adjust_stock!(amount)
    @batch_price = BatchPrice.where(:consumable_id => self.consumable.id).first
    @batch_price.stock += amount
    @batch_price.save!
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_admin!, :except => [:new, :create]

  layout 'application'
  layout 'front', :only => :new

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.paginate page: params[:page], order: 'updated_at desc', per_page: 50

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end
  
  # GET /orders/track
  # GET /orders/track.json
  def track 
    @pending = Order.pending
    @awaiting = Order.awaiting
    @dispatched = Order.dispatched
    @deleted = Order.deleted

    respond_to do |format|
      format.html
      format.json { render json: @order }
    end
  end

  # PUT /orders/dispatch
  # PUT /orders/dispatch.json
  def complete
    @order = Order.find(params[:id])
    @order.order_status = "DIS"
    @order.adjust_stock!(-1)
    
    respond_to do |format|
      if @order.save
        format.html { 
          redirect_to tracking_path, 
          :notice => "#{@order.consumable.full_name} for #{@order.printer_names} Dispatched to #{@order.location}"
        }
        format.json { render json: @order }
      else
        @order.adjust_stock!(+1)
        format.html {
          redirect_to tracking_path,
          flash.now[:error] = "Error dispatching consumable, are there any in stock?"
        }
      end
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new
    @printers = PrinterModel.all.sort
    @consumables = Consumable.all
    @departments = Department.order(:name)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
    @printers = PrinterModel.all.sort
    @consumables = Consumable.all
    @departments = Department.order(:name)
  end

  # POST /orders
  # POST /orders.json
  def create
    params[:order] = params[:order].except(:printer_models)
    @order = Order.new(params[:order])
    @order.department = Department.find(params[:order][:department_id])
    @order.consumable = Consumable.find(params[:order][:consumable_id])
    @order.calculate_order_status
    @order.price = @order.consumable.batch_price.price
    
    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url, :flash => { :result => 'sent' }, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: root_url }
      else
        format.html {
          flash.now[:error] = "There was an error"
          render :new 
        }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    #Orders are never destroyed, this action instead sets it to a DELETED state.

    @order = Order.find(params[:id])
    @order.order_status = "DEL"

    respond_to do |format|
      if @order.save
        format.html { redirect_to orders_url }
        format.json { head :ok }
        format.js
      else
        raise
      end
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2>Sorry, couldn't place your order. Please address the <%= pluralize(@order.errors.count, "field") %> below:</h2>
      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location, :size => 40 %>
  </div>
  <div class="field">
    <%= f.label :department_id %><br />
    <%= f.collection_select :department_id,  @departments, :id, :name, :prompt => "Please select your department" %>
  </div>
  <div class="field">
    <%= label_tag 'order_printer_models', "Printer Model" %><br />
    <%=f.collection_select :printer_models, @printers, :id, :full_name, :prompt => "Please select your printer..." %>
  </div>
  <div class="field">
    <%= f.label :consumable_id, "Required Consumable" %><br />
    <%= f.grouped_collection_select :consumable_id, @printers, :consumables, :full_name, :id, :grouped_description_with_stock, :prompt => "Please select a printer first." %>
  </div><br />
  <div class="actions">
    <%= f.submit "Place Order" %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<tr class="<%= cycle("even", "odd") %>" id="order-<%= order.id %>">
  <td><%= order.created_at.strftime('%H:%M:%S %d/%m/%Y') %></td>
  <td class="order-updated-at">
  <%= "#{order.updated_at.strftime('%H:%M:%S %d/%m/%Y')}" unless order.updated_at == order.created_at %>
  </td>
  <td><%= order.location %></td>
  <td><%= link_to order.consumable.full_name, order.consumable %></td>
  <td><%= number_to_currency order.price %></td>
  <td class="order-status <%= order.order_status %>"><%= order.order_status_text %></td>
  <td><%= link_to 'Edit', edit_order_path(order) %></td>
  <td><%= link_to 'Cancel', order, confirm: 'Are you sure?', method: :delete, :class => "cancel-link", remote: true unless ["DEL","DIS", "FOC"].include? order.order_status %></td>
</tr>

app/views/orders/destroy.js.erb
$("#order-<%= @order.id %>").removeClass("red-out green-out")
$("#order-<%= @order.id %>").addClass("grey-out")
$("#order-<%= @order.id %>").find('a.cancel-link').hide()
$("#order-<%= @order.id %>").find('td.order-status').text("Deleted")
$("#order-<%= @order.id %>").find('td.order-updated-at').text("<%= @order.updated_at.strftime('%H:%M:%S %d/%m/%Y') %>")

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<%= render :partial => "shared/title" %>

<table class="table table-bordered">
  <tr>
    <th>Ordered</th>
    <th>Last Updated</th>
    <th>Location</th>
    <th>Requested Consumable</th>
    <th>Price</th>
    <th>Order status</th>
    <th colspan="2">Actions</th>
  </tr>

<%= render @orders %>

</table>

<br />
<p><%= will_paginate @orders %></p>

app/views/orders/new.html.erb
<%= image_tag 'order_header.png', :alt => "Need toner?" %>
<%= render 'form' %>

app/views/orders/show.html.erb
<p>
  <b>Location:</b>
  <%= @order.location %>
</p>

<p>
  <b>Price:</b>
  <%= @order.price %>
</p>

<p>
  <b>Order status:</b>
  <%= @order.order_status %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/orders/track.html.erb
<!-- tracking action -->

<%= render :partial => "shared/title" %>

<% unless @pending.empty? %>
  <div class="pending_orders">
  <h2>Pending</h2>
  <table>
    <tr>
      <th>Location</th>
      <th>Printer(s)</th>
      <th>Consumable</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @pending.each do |order| %>
    <tr class="<%= cycle("even", "odd") %>">
      <td><%= order.location %></td>
      <td><%= order.printer_names %></td>
      <td><%= order.consumable_name(:with_type) %></td>
      <td><%= link_to 'Edit', edit_order_path(order) %></td>
      <td><%= link_to 'Dispatch', complete_order_path(order), method: :put %></td>
      <td><%= link_to 'Cancel', order, confirm: 'Are you sure?', method: :delete %></td>
      <td class="pending-time"><%= "#{time_ago_in_words(order.created_at).gsub('about', '~')} ago" %></td>
    </tr>
  <% end %>
  </table>
  </div>
<% else %>
<p>No orders pending</p>
<% end %>
<% unless @awaiting.empty? %>
  <div class="awaiting_orders">
    <h2>Awaiting Stock</h2>
  <table>
    <tr>
      <th>Location</th>
      <th>Printer(s)</th>
      <th>Consumable</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  <% @awaiting.each do |order| %>
    <tr class="<%= cycle("even", "odd") %>">
      <td><%= order.location %></td>
      <td><%= order.printer_names %></td>
      <td><%= order.consumable_name(:with_type) %></td>
      <td><%= link_to 'Edit', edit_order_path(order) %></td>
      <td><%= link_to 'Cancel', order, confirm: 'Are you sure?', method: :delete %></td>
      <td class="awaiting-time"><%= "#{time_ago_in_words(order.created_at).gsub('about', '~')} ago" %></td>
    </tr>
  <% end %>
  </table>
  </div>
<% else %>
<p>No orders awaiting stock</p>
<% end %>