config/routes.rb
R3TMS::Application.routes.draw do
  devise_for :admins
  
  match 'manage/:controller', :controller => ':controller', :action => 'index'
  match 'manage/:controller/:action', :to => ':controller/:action'
  
  match 'manage', :controller => 'orders', :action => 'track'

  match 'tracking', :controller => 'orders', :action => 'track'
  match 'track', :controller => 'orders', :action => 'track'
  
  resources :orders do
    put :complete, :on => :member
  end
  
  resources :consumables

  resources :printer_models

  resources :batches

  resources :suppliers

  resources :departments

  resources :manufacturers

  root :to => 'orders#new'
end

app/models/consumable.rb
# == Schema Information
#
# Table name: consumables
#
#  id          :integer          not null, primary key
#  description :string(255)
#  reorder_no  :string(255)
#  kind        :string(255)
#  supplier_id :integer
#  order_id    :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Consumable < ActiveRecord::Base
  has_and_belongs_to_many :printer_models
  belongs_to :supplier
  has_many :manufacturers, :through => :printer_models
  has_many :orders
  has_one :batch_price
  has_one :batch, :through => :batch_price

  attr_accessible :description, :reorder_no, :kind, :supplier_id, :order_ids, :batch, :printer_model_ids

  accepts_nested_attributes_for :batch_price

  KINDS = [ "REM", "REM-HICAP", "OEM", "OEM-HICAP" ]
  validates :description, :reorder_no, :batch_price, :presence => true
  validates :kind, inclusion: KINDS

  def full_name
    "#{self.supplier.name}/#{reorder_no}"
  end

  def effective_stock
    self.batch_price.stock - Order.where(:consumable_id => self.id, :order_status => "PEN").count
  end

  def description_with_stock
    if self.batch_price.stock >= 1 
      "#{self.description} (#{self.effective_stock} available)" 
    else
      "#{self.description} (out of stock)" 
    end
  end

  def grouped_description_with_stock
    effective_stock_total = 0
    Consumable.all.each do |consumable|
      begin
        effective_stock_total += consumable.effective_stock
      end unless ((consumable.printer_model_ids & self.printer_model_ids).empty?) or (consumable.description != self.description)
    end

    if effective_stock_total >= 1 
      "#{self.description} (#{effective_stock_total} available)"
    else
      "#{self.description} (out of stock)" 
    end
  end
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id            :integer          not null, primary key
#  location      :string(255)
#  price         :decimal(3, 2)
#  order_status  :string(255)
#  department_id :integer
#  consumable_id :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class Order < ActiveRecord::Base
  attr_accessible :location, :department_id, :consumable_id, :printer_models

  belongs_to :department
  belongs_to :consumable
  has_many :printer_models, :through => :consumable

  # Possible order statuses, don't forget to add relevent scope!

  STATUS = {
              "PEN" => "Pending Dispatch",
              "AWS" => "Awaiting Stock",
              "DIS" => "Dispatched",
              "DEL" => "Deleted",
              "FOC" => "Free of Charge",
              "ADD" => "Added to Stock"
            }

  validates :location, :price, :order_status, :department_id, :consumable_id, :presence => true
  validates :order_status, :inclusion => { :in => STATUS }

  #scopes
  scope :status, ->(stat) { where("orders.order_status LIKE ?", stat) }

  scope :pending, order.status("PEN")
  scope :awaiting, order.status("AWS")
  scope :deleted, order.status("DEL")
  scope :dispatched, order.status("DIS")
  scope :free, order.status("FOC")
  scope :added, order.status("ADD")

  def calculate_order_status
    stock = self.consumable.batch_price.stock
    if stock >= 1
      self.order_status = "PEN"
    elsif stock == 0
      self.order_status = "AWS"
    end
  end

  def order_status_text
    STATUS[order_status]
  end

  def consumable_name(type=false)
    consumable = Consumable.find(self.consumable_id)
    type ? "#{consumable.full_name}, #{consumable.description} (#{consumable.kind})" : "#{consumable.full_name}, #{consumable.description}"
  end

  def printer_names
    result = []
    self.consumable.printer_models.each do |printer|
      result << printer.full_name
    end
    result.to_sentence
  end

  def adjust_stock!(amount)
    @batch_price = BatchPrice.where(:consumable_id => self.consumable.id).first
    @batch_price.stock += amount
    @batch_price.save!
  end
end

app/controllers/consumables_controller.rb
class ConsumablesController < ApplicationController
  before_filter :authenticate_admin!, :get_all_batches

  # GET /consumables
  # GET /consumables.json
  def index
    @consumables = Consumable.paginate(:page => params[:page] || 1, :per_page => 10).order('description DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @consumables }
    end
  end

  # GET /consumables/1
  # GET /consumables/1.json
  def show
    @consumable = Consumable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @consumable }
    end
  end

  # GET /consumables/new
  # GET /consumables/new.json
  def new
    get_all_batches
    @consumable = Consumable.new
    @price = BatchPrice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @consumable }
    end
  end

  # GET /consumables/1/edit
  def edit
    @consumable = Consumable.find(params[:id])
    @price = @consumable.batch_price
  end

  # POST /consumables
  # POST /consumables.json
  def create
    @consumable = Consumable.new(params[:consumable].except(params[:consumable][:batch]))
    @price = @consumable.build_batch_price(
        :batch_id => Batch.find(params[:batch_price][:batch]),
        :consumable => @consumable,
        :price => params[:batch_price][:price],
        :stock => params[:batch_price][:stock]
      )

    respond_to do |format|
      if @consumable.save
        format.html { redirect_to consumables_path,
                      notice: 'Consumable was successfully created.'
                    }
        format.json { render json: @consumable, status: :created, location: @consumable }
      else
        format.html { render action: "new" }
        format.json { render json: @consumable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /consumables/1
  # PUT /consumables/1.json
  def update
    @consumable = Consumable.find(params[:id])
    # @consumable.batch_price.batch = Batch.find(params[:batch_price][:batch])
    @consumable.update_attributes(params[:consumable])

    respond_to do |format|
      if @consumable.save
        format.html { redirect_to consumables_path,
                      notice: "Consumable was successfully updated."
                    }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @consumable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consumables/1
  # DELETE /consumables/1.json
  def destroy
    @consumable = Consumable.find(params[:id])
    @consumable.destroy

    respond_to do |format|
      format.html { redirect_to consumables_url }
      format.json { head :ok }
    end
  end

  protected
  def get_all_batches
    @batches = Batch.all
  end
end

app/helpers/consumables_helper.rb
module ConsumablesHelper
end

app/views/consumables/_consumable.html.erb
<tr class="<%= cycle("even", "odd") %>">
  <td><%= link_to consumable.batch.nil?, consumable.batch.batch_id %></td>
  <td><%= link_to consumable.full_name, edit_consumable_path(consumable.id) %></td>
  <td><%= consumable.description %></td>
  <td>
    <ul>
    <% consumable.printer_models.each do |printer| %>
    <li><%= printer.full_name %></li>
    <% end %>
    </ul>
  </td>
  <td><%= consumable.kind %></td>
  <td>£ <%= consumable.batch_price.price.to_s unless consumable.batch_price.nil? %></td>
  <td><%= consumable.batch_price.stock.to_s %></td>
  <td><%= link_to 'Delete', consumable, confirm: "Permanently delete #{consumable.full_name}?", method: :delete %></td>
</tr>

app/views/consumables/_form.html.erb
<%= form_for(@consumable) do |f| %>
  <% if @consumable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consumable.errors.count, "error") %> prohibited this consumable from being saved:</h2>
      <ul>
      <% @consumable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      <% @price.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <legend>Consumable</legend>
    <% if @batches.empty? %>
      <p><%= link_to "Add the first batch before continuing", new_batch_path %></p>
    <% else %>
    <% if @consumable.batch_price.nil? %>
      <%= fields_for(@price) do | builder | %>
        <div class="field">
          <%= builder.label :batch, "Batch" %>
          <%= builder.collection_select :batch, @batches, :id, :batch_id, :prompt => "Please select..." %>
        </div>
      <% end %>
    <% else %>
      <%= fields_for(@price) do | builder | %>
        <div class="field">
          <%= builder.label :batch, "Batch" %>
          <%= builder.hidden_field :batch, "#{@consumable.batch_price.batch.id}" %>
          <b><%= @consumable.batch_price.batch.batch_id %></b>
        </div>
      <% end %>
    <% end %>
    <div class="field">
      <%= f.label :description %> e.g. "Black Toner"<br />
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :supplier_id, "Supplier" %><br />
      <%= f.collection_select :supplier_id,
                              Supplier.all,
                              :id,
                              :name,
                              :prompt => "Select supplier..."
      %>
    </div>
    <div class="field">
      <%= f.label :reorder_no, "Supplier Reorder Number" %><br />
      <%= f.text_field :reorder_no %>
    </div>
    <div class="field">
      <%= f.label :kind, "Type" %><br />
      <%= f.select :kind,
                   Consumable::KINDS,
                   prompt: 'Select a type...',
                   :selected => @consumable.kind 
      %>
    </div>
    <%= fields_for(@price) do | builder | %>
    <div class="field">
      <%= builder.label :price, "Price (£)" %><br />
      <%= builder.text_field :price %>
    </div>
    <% end %><br />
    <fieldset>
      <legend>Compatible Printers</legend>
      <div class="field">
        <% for manufacturer in Manufacturer.all %>
          <% printer = manufacturer.printer_models %>
          <% if printer.empty? %>
            <p class="bold manufacturer-title">No <%= manufacturer.name %> printers: <%= link_to "Add one.", new_printer_model_path %></p>
          <% else %>
            <p class="bold manufacturer-title"><%= manufacturer.name %>:</p>
            <% printer.each do |p| %>
              <label class="selectable">
                <div class="printer-thumb">
                  <% if p.image.exists? then %>
                    <%= image_tag p.image.url(:thumb) %> <br />
                  <% else %>
                    <%= content_tag :p, "Add an image for this printer!" %>
                  <% end %>
                  <%= check_box_tag "consumable[printer_model_ids][]", p.id,
                                 @consumable.printer_models.include?(p), :class => "hidden"
                  %>
                  <p><%= p.full_name %></p>
                </div> 
              </label>
            <% end %>
          <% end %>
        <% end %>
      </div> 
    </fieldset><br />
    <%= fields_for(@price) do | builder | %>
      <div class="field">
        <%= builder.label :stock, "# In Stock" %><br />
        <%= builder.text_field :stock %>
      </div>
    <% end %><br />
    <div class="actions">
      <%= f.submit %>
    </div>
     <% end %>
  </fieldset>
<% end %>

app/views/consumables/edit.html.erb
<h1>Editing Consumable <%= @consumable.full_name %></h1>

<%= render 'form' %>

<%= link_to 'Back', consumables_path %>

app/views/consumables/index.html.erb
<%= render :partial => "shared/title" %>

<table>
  <tr>
    <th>Batch</th>
    <th>Consumable<br />(Supplier/Reorder)</th>
    <th>Description</th>
    <th>Compatible Printers</th>
    <th>Type</th>
    <th>Price</th>
    <th>Current Stock</th>
    <th>Actions</th>
  </tr>
<%= render @consumables %>

</table>

<br />
<p><%= will_paginate @consumables %></p>
<%= link_to "#{image_tag('icons/page_new.gif', :alt => 'New Consumable')} New Consumable", new_consumable_path %>

app/views/consumables/new.html.erb
<h1>New consumable</h1>

<%= render 'form' %>

<%= link_to 'Back', consumables_path %>

app/views/consumables/show.html.erb
<p>
  <b>Description:</b>
  <%= @consumable.description %>
</p>

<p>
  <b>Consumable:</b>
  <%= @consumable.full_name %>
</p>

<p>
  <b>Type:</b>
  <%= @consumable.kind %>
</p>


<%= link_to 'Edit', edit_consumable_path(@consumable) %> |
<%= link_to 'Back', consumables_path %>